[tool.black]
line-length = 80
target-version = ["py311"]
skip-string-normalization = true

[tool.ruff]
line-length = 79
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "W", "I", "N", "UP", "A", "B", "COM", "C4", "Q"]
ignore = ["C901"]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"
